---
- name: ast-grep
  hosts: localhost
  roles:
    - role: cargo
      vars:
        url: 'https://github.com/ast-grep/ast-grep.git'
        repo_dir: ast-grep
        version: d64c8606a54e4892c251514f5673e42c4f9c5051
        package_name: ast-grep
        build_root: ['crates', 'cli']
        completions:
          executable: ast-grep
          args:
            - completions
            - zsh
