---
- name: eza
  hosts: localhost
  roles:
    - role: cargo
      vars:
        url: 'https://github.com/eza-community/eza.git'
        repo_dir: eza
        version: a72d4fdd580b5310894ac44b7f8a71b693ba458d
        package_name: eza
        build_root: []
