---
- name: fd
  hosts: localhost
  roles:
    - role: cargo
      vars:
        url: 'https://github.com/sharkdp/fd.git'
        repo_dir: fd
        version: ba35c5ea67d995dfd12001678af7d4533c7d5458
        package_name: fd-find
        build_root: []
