---
- name: go
  hosts: localhost
  tasks:
    - name: Clone
      ansible.builtin.git:
        repo: 'https://go.googlesource.com/go'
        dest: "{{ [distfiles_dir, 'go'] | path_join }}"
        depth: 1
        single_branch: true
        version: d4c6effaa7b95a2ea149ece4a400c0ace2773839

    - name: Build
      ansible.builtin.command:
        cmd: ./all.bash
        creates: "{{ [distfiles_dir, 'go', 'bin'] | path_join }}"
        chdir: "{{ [distfiles_dir, 'go', 'src'] | path_join }}"

    - name: Install
      ansible.builtin.copy:
        src: "{{ [distfiles_dir, 'go', 'bin'] | path_join }}/"
        dest: "{{ ['/', 'usr', 'local', 'bin'] | path_join }}"
        mode: 'u=rwx,g=rx,o=rx'
      become: true

    - name: Cleanup
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ [distfiles_dir, 'go', 'bin'] | path_join }}"
        - "{{ [lookup('ansible.builtin.env', 'HOME'), 'go'] | path_join }}"
