---
- name: Install atuin
  ansible.builtin.import_playbook: atuin.yaml

- name: Install bat
  ansible.builtin.import_playbook: bat.yaml

- name: Install cargo
  ansible.builtin.import_playbook: cargo.yaml
  tags:
    - dependencies

- name: Install go
  ansible.builtin.import_playbook: go.yaml
  tags:
    - dependencies
    - long-running

- name: Install glow
  ansible.builtin.import_playbook: glow.yaml

- name: Install libevent
  ansible.builtin.import_playbook: libevent.yaml
  tags:
    - dependencies
    - long-running

- name: Install ncurses
  ansible.builtin.import_playbook: ncurses.yaml
  tags:
    - dependencies
    - long-running

- name: Install ast-grep
  ansible.builtin.import_playbook: ast-grep.yaml

- name: Install btop
  ansible.builtin.import_playbook: btop.yaml

- name: Install dzen2
  ansible.builtin.import_playbook: dzen2.yaml

- name: Install eza
  ansible.builtin.import_playbook: eza.yaml

- name: Install fastfetch
  ansible.builtin.import_playbook: fastfetch.yaml

- name: Install fd
  ansible.builtin.import_playbook: fd.yaml

- name: Install font
  ansible.builtin.import_playbook: font.yaml

- name: Install fzf-tab
  ansible.builtin.import_playbook: fzf-tab.yaml

- name: Install fzf
  ansible.builtin.import_playbook: fzf.yaml

- name: Install fzfmenu
  ansible.builtin.import_playbook: fzfmenu.yaml

- name: Install fzfpassmenu
  ansible.builtin.import_playbook: fzfpassmenu.yaml

- name: Install neovim
  ansible.builtin.import_playbook: neovim.yaml
  tags:
    - long-running

- name: Install pass
  ansible.builtin.import_playbook: pass.yaml

- name: Install ripgrep
  ansible.builtin.import_playbook: ripgrep.yaml

- name: Install starship
  ansible.builtin.import_playbook: starship.yaml

- name: Install tmux
  ansible.builtin.import_playbook: tmux.yaml

- name: Install uv
  ansible.builtin.import_playbook: uv.yaml
  tags:
    - long-running

- name: Install zoxide
  ansible.builtin.import_playbook: zoxide.yaml

- name: Install zsh-autosuggestions
  ansible.builtin.import_playbook: zsh-autosuggestions.yaml

- name: Install zsh-completions
  ansible.builtin.import_playbook: zsh-completions.yaml

- name: Install zsh-history-substring-search
  ansible.builtin.import_playbook: zsh-history-substring-search.yaml

- name: Install zsh-syntax-highlighting
  ansible.builtin.import_playbook: zsh-syntax-highlighting.yaml
