---
- name: ripgrep
  hosts: localhost
  roles:
    - role: cargo
      vars:
        url: 'https://github.com/BurntSushi/ripgrep.git'
        repo_dir: ripgrep
        version: cbc598f245f3c157a872b69102653e2e349b6d92
        package_name: ripgrep
        build_root: []
