---
- name: ast-grep
  hosts: localhost
  roles:
    - role: cargo
      vars:
        url: 'https://github.com/ast-grep/ast-grep.git'
        repo_dir: ast-grep
        version: "{{ env_lock['ast-grep'] }}"
        package_name: ast-grep
        build_root: ['crates', 'cli']
        completions:
          executable: ast-grep
          argv:
            - completions
            - zsh
