---
- name: atuin
  hosts: localhost
  roles:
    - role: cargo
      vars:
        url: 'https://github.com/atuinsh/atuin'
        repo_dir: atuin
        version: e6ab243dfde79c50ce5661b630ed26b9a1504dae
        package_name: atuin
        build_root: ['crates', 'atuin']
        completions:
          executable: atuin
          args:
            - gen-completions
            - --shell
            - zsh
