---
- name: eza
  hosts: localhost
  roles:
    - role: cargo
      vars:
        url: 'https://github.com/eza-community/eza.git'
        repo_dir: eza
        version: 08152f891c680f890afa384c2d4012c0eacc025c
        package_name: eza
        build_root: []
