---
- name: eza
  hosts: localhost
  roles:
    - role: cargo
      vars:
        url: 'https://github.com/eza-community/eza.git'
        repo_dir: eza
        version: "{{ env_lock['eza'] }}"
        package_name: eza
        build_root: []
