---
- name: fd
  hosts: localhost
  roles:
    - role: cargo
      vars:
        url: 'https://github.com/sharkdp/fd.git'
        repo_dir: fd
        version: "{{ env_lock['fd'] }}"
        package_name: fd-find
        build_root: []
