---
- name: fd
  hosts: localhost
  roles:
    - role: cargo
      vars:
        url: 'https://github.com/sharkdp/fd.git'
        repo_dir: fd
        version: ff1f66cceb981866416a8611ad264340885cb6b2
        package_name: fd-find
        build_root: []
