---
- name: fzfmenu
  hosts: localhost
  tasks:
    - name: Clone
      ansible.builtin.git:
        repo: 'https://github.com/illia-shkroba/fzfmenu.git'
        dest: "{{ [distfiles_dir, 'fzfmenu'] | path_join }}"
        single_branch: true
        version: f02153003036a581f47c4486629baa1f9de965a9

    - name: Create root directories
      ansible.builtin.file:
        path: "{{ ['/', 'usr', 'local', 'bin'] | path_join }}"
        state: directory
      become: true

    - name: Copy scripts
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ ['/', 'usr', 'local', 'bin'] | path_join }}"
        mode: 'u=rwx,g=rx,o=rx'
      loop:
        - "{{ [distfiles_dir, 'fzfmenu', 'fzfmenu'] | path_join }}"
        - "{{ [distfiles_dir, 'fzfmenu', 'fzfmenu-run'] | path_join }}"
      become: true
