---
- name: fzfmenu
  hosts: localhost
  tasks:
    - name: Clone
      ansible.builtin.git:
        repo: 'https://github.com/illia-shkroba/fzfmenu.git'
        dest: "{{ [distfiles_dir, 'fzfmenu'] | path_join }}"
        single_branch: true
        version: 91889430596349cf14d3eb1108c9cba3ab3f5b9d

    - name: Create root directories
      ansible.builtin.file:
        path: "{{ ['/', 'usr', 'local', 'bin'] | path_join }}"
        state: directory
      become: true

    - name: Install
      community.general.make:
        target: install
        chdir: "{{ [distfiles_dir, 'fzfmenu'] | path_join }}"
        params:
          DESTDIR: /
      become: true
