---
- name: ripgrep
  hosts: localhost
  roles:
    - role: cargo
      vars:
        url: 'https://github.com/BurntSushi/ripgrep.git'
        repo_dir: ripgrep
        version: "{{ env_lock['ripgrep'] }}"
        package_name: ripgrep
        build_root: []
