---
- name: starship
  hosts: localhost
  tasks:
    - name: Clone
      ansible.builtin.git:
        repo: 'https://github.com/starship/starship.git'
        dest: "{{ [distfiles_dir, 'starship'] | path_join }}"
        single_branch: true
        version: 8952f47d908e09a12de9681b404cfebe0cf5b945

    - name: Install
      ansible.builtin.command:
        cmd: ./install/install.sh --yes
        chdir: "{{ [distfiles_dir, 'starship'] | path_join }}"
      become: true
