---
- name: tree-sitter
  hosts: localhost
  roles:
    - role: cargo
      vars:
        url: 'https://github.com/tree-sitter/tree-sitter'
        repo_dir: tree-sitter
        version: cf302b07d1cae984068b7eb44a6e44529566a8c9
        package_name: tree-sitter-cli
        build_root: ['crates', 'cli']
        completions:
          executable: tree-sitter
          args:
            - complete
            - --shell
            - zsh
