---
- name: zsh-autosuggestions
  hosts: localhost
  tasks:
    - name: Clone
      ansible.builtin.git:
        repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
        dest: "{{ [distfiles_dir, 'zsh-autosuggestions'] | path_join }}"
        single_branch: true
        version: 0e810e5afa27acbd074398eefbe28d13005dbc15

    - name: Create root directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ ['/', 'usr', 'share', 'zsh', 'plugins', 'zsh-autosuggestions'] | path_join }}"
        - "{{ ['/', 'usr', 'share', 'doc', 'zsh-autosuggestions'] | path_join }}"
      become: true

    - name: Copy script
      ansible.builtin.copy:
        src: "{{ [distfiles_dir, 'zsh-autosuggestions', 'zsh-autosuggestions.zsh'] | path_join }}"
        dest: "{{ ['/', 'usr', 'share', 'zsh', 'plugins', 'zsh-autosuggestions'] | path_join }}"
        mode: 'u=rwx,g=rx,o=rx'
      become: true

    - name: Copy manual
      ansible.builtin.copy:
        src: "{{ [distfiles_dir, 'zsh-autosuggestions', 'README.md'] | path_join }}"
        dest: "{{ ['/', 'usr', 'share', 'doc', 'zsh-autosuggestions'] | path_join }}"
        mode: 'u=rw,g=r,o=r'
      become: true
