---
- name: zsh
  hosts: localhost
  vars:
    patches:
      - "{{ [playbook_dir, '..', 'etc', 'zsh', '0001-50629-do-not-use-egrep-in-tests.patch'] | path_join }}"
      - "{{ [playbook_dir, '..', 'etc', 'zsh', '0001-50641-use-int-main.patch'] | path_join }}"
      - "{{ [playbook_dir, '..', 'etc', 'zsh', '0002-50325-fix-autocompletion.patch'] | path_join }}"
      - "{{ [playbook_dir, '..', 'etc', 'zsh', '0003-51862-support-texinfo-7-0.patch'] | path_join }}"
      - "{{ [playbook_dir, '..', 'etc', 'zsh', '0004-pcre2.patch'] | path_join }}"
      - "{{ [playbook_dir, '..', 'etc', 'zsh', '0005-52383-avoid-incompatible-pointer-types.patch'] | path_join }}"
  tasks:
    - name: Download archive
      ansible.builtin.get_url:
        url: https://www.zsh.org/pub/zsh-5.9.tar.xz
        dest: "{{ [distfiles_dir, 'zsh-5.9.tar.xz'] | path_join }}"
        checksum: sha256:9b8d1ecedd5b5e81fbf1918e876752a7dd948e05c1a0dba10ab863842d45acd5

    - name: Unpack archive
      ansible.builtin.unarchive:
        src: "{{ [distfiles_dir, 'zsh-5.9.tar.xz'] | path_join }}"
        dest: "{{ [distfiles_dir] | path_join }}"

    - name: Remove archive
      ansible.builtin.file:
        path: "{{ [distfiles_dir, 'zsh-5.9.tar.xz'] | path_join }}"
        state: absent

    - name: Apply build fix patches
      ansible.posix.patch:
        src: "{{ item }}"
        basedir: "{{ [distfiles_dir, 'zsh-5.9'] | path_join }}"
        strip: 1
      loop: "{{ patches }}"

    - name: Set correct keymap path
      ansible.builtin.replace:
        path: "{{ [distfiles_dir, 'zsh-5.9', 'Completion', 'Unix', 'Command', '_loadkeys'] | path_join }}"
        regexp: '/usr/share/keymaps'
        replace: '/usr/share/kbd/keymaps'

    - name: Fix usb.ids path
      ansible.builtin.replace:
        path: "{{ [distfiles_dir, 'zsh-5.9', 'Completion', 'Linux', 'Command', '_lsusb'] | path_join }}"
        regexp: '/usr/share/misc/usb\.ids'
        replace: '/usr/share/hwdata/usb.ids'

    - name: Force generation of documentation with correct paths
      ansible.builtin.file:
        path: "{{ [distfiles_dir, 'zsh-5.9', 'Doc', 'version.yo'] | path_join }}"
        state: absent

    - name: Regenerate `configure` after patching
      ansible.builtin.command:
        cmd: autoreconf -fi
        chdir: "{{ [distfiles_dir, 'zsh-5.9'] | path_join }}"

    - name: Configure
      ansible.builtin.command:
        argv:
          - ./configure
          - --prefix=/usr
          - --docdir=/usr/share/doc/zsh
          - --htmldir=/usr/share/doc/zsh/html
          - --enable-etcdir=/etc/zsh
          - --enable-zshenv=/etc/zsh/zshenv
          - --enable-zlogin=/etc/zsh/zlogin
          - --enable-zlogout=/etc/zsh/zlogout
          - --enable-zprofile=/etc/zsh/zprofile
          - --enable-zshrc=/etc/zsh/zshrc
          - --enable-maildir-support
          - --with-term-lib=ncursesw
          - --enable-multibyte
          - --enable-function-subdirs
          - --enable-fndir=/usr/share/zsh/functions
          - --enable-scriptdir=/usr/share/zsh/scripts
          - --with-tcsetpgrp
          - --enable-pcre
          - --enable-gdbm
          - --enable-cap
          - --enable-zsh-secure-free
        chdir: "{{ [distfiles_dir, 'zsh-5.9'] | path_join }}"

    - name: Build
      community.general.make:
        chdir: "{{ [distfiles_dir, 'zsh-5.9'] | path_join }}"

    - name: Install
      community.general.make:
        target: install
        chdir: "{{ [distfiles_dir, 'zsh-5.9'] | path_join }}"
        params:
          DESTDIR: /
      become: true

    - name: Copy zprofile
      ansible.builtin.copy:
        src: "{{ [playbook_dir, '..', 'etc', 'zsh', 'zprofile'] | path_join }}"
        dest: "{{ ['/', 'etc', 'zsh', 'zprofile'] | path_join }}"
        mode: '0644'
      become: true

    - name: Add zsh to a list of shells
      ansible.builtin.lineinfile:
        path: "{{ ['/', 'etc', 'shells'] | path_join }}"
        line: "{{ item }}"
      loop:
        - '^/bin/zsh$'
        - '^/usr/bin/zsh$'
      become: true
